<script setup lang="ts">
import { ref } from 'vue'
import { ChevronDown } from 'lucide-vue-next'
const openFaqs = ref<number[]>([0])
function toggleFaq(index: number) { openFaqs.value = openFaqs.value.includes(index) ? openFaqs.value.filter(i => i !== index) : [...openFaqs.value, index] }
function isOpen(index: number) { return openFaqs.value.includes(index) }
const faqs = [
  { q: 'Как начать играть на Breeze?', a: '1. Авторизуйтесь на сайте через Discord.\n2. Приобретите проходку.\n3. Скачайте наш Breeze Launcher (сборка с модами и обновления скачаются автоматически).' },
  { q: 'Какие системные требования у сборки?', isSpecs: true, specs: { min: { title: 'Минимальные (45–60 FPS)', cpu: 'Intel Core i3 10-го пок. / AMD Ryzen 3 3100', ram: '8 ГБ (выделить 5–6 ГБ в лаунчере)', gpu: 'GTX 960 / GTX 1050 / Radeon RX 560 (от 2 ГБ VRAM)', disk: 'SSD обязателен (от 6 ГБ свободно)', note: 'Низко-средние настройки, без шейдеров, базовый Distant Horizons.' }, rec: { title: 'Рекомендуемые (60–120+ FPS)', cpu: 'Intel Core i5 12400F / AMD Ryzen 5 5600', ram: '16 ГБ (выделить 6–8 ГБ в лаунчере)', gpu: 'RTX 2060 / GTX 1660 Super / RX 6600 (от 6 ГБ VRAM)', disk: 'Быстрый NVMe SSD', note: 'Высокие настройки с шейдерами и максимальной дальностью LOD-чанков.' } } },
  { q: 'Нужна ли лицензия Minecraft?', a: 'Нет. В наш лаунчер Breeze встроен независимый клиент, авторизация и скины привязаны к вашему Discord-аккаунту.' },
  { q: 'Зачем платить за проходку?', a: 'Платный вход отсекает читеров, ботов и неадекватных игроков. Мы поддерживаем чистое ламповое полу-РП комьюнити без доната, влияющего на баланс.' },
  { q: 'Что если меня загриферили или взорвали пушкой?', a: 'На сервере ведется полное логирование каждого блока и действия. Создайте тикет в нашем Discord — администрация откатит ущерб, а нарушитель получит бан.' },
  { q: 'Есть ли голосовой чат?', a: 'Да, в сборку встроен позиционный Simple Voice Chat с поддержкой акустики пещер и помещений. Микрофон настраивается прямо в игре.' }
]
</script>
<template><section id="faq" class="w-full max-w-4xl mx-auto px-4 py-16 flex flex-col items-center"><h2 class="text-3xl sm:text-4xl font-black text-[var(--text-main)] text-center mb-10 tracking-tight">Вопросы и ответы</h2><div class="w-full flex flex-col gap-3"><div v-for="(item, index) in faqs" :key="item.q" class="w-full bg-[var(--bg-card)] border-[var(--border-color)] rounded-2xl overflow-hidden transition-all duration-200" :class="{ 'border-[#0080FF]/40 shadow-lg shadow-[#0080FF]/5': isOpen(index) }"><button type="button" @click="toggleFaq(index)" class="w-full px-6 py-5 flex items-center justify-between text-left text-base font-semibold text-[var(--text-main)] hover:text-[var(--text-main)] bg-transparent border-0 cursor-pointer outline-none"><span>{{ item.q }}</span><ChevronDown :size="18" class="transition-transform duration-200 shrink-0 ml-3 text-[var(--text-muted)]" :class="{ 'rotate-180 text-[#00BBFF]': isOpen(index) }" /></button><div v-if="isOpen(index)" class="px-6 pb-6 text-sm text-[var(--text-muted)] leading-relaxed border-t border-[var(--border-color)] pt-4"><div v-if="item.isSpecs" class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2"><div class="bg-black/30 border border-white/[0.06] rounded-xl p-4 flex flex-col justify-between"><div><span class="inline-block px-2.5 py-0.5 rounded-md bg-white/10 text-xs font-bold text-[var(--text-muted)] mb-3">{{ item.specs.min.title }}</span><ul class="space-y-2 text-xs text-[var(--text-muted)]"><li><strong class="text-[var(--text-muted)]">Процессор:</strong> {{ item.specs.min.cpu }}</li><li><strong class="text-[var(--text-muted)]">ОЗУ:</strong> {{ item.specs.min.ram }}</li><li><strong class="text-[var(--text-muted)]">Видеокарта:</strong> {{ item.specs.min.gpu }}</li><li><strong class="text-[var(--text-muted)]">Накопитель:</strong> {{ item.specs.min.disk }}</li></ul></div><p class="text-[11px] text-slate-500 mt-4 border-t border-white/[0.05] pt-2">{{ item.specs.min.note }}</p></div><div class="bg-black/30 border border-[#0080FF]/30 rounded-xl p-4 flex flex-col justify-between"><div><span class="inline-block px-2.5 py-0.5 rounded-md bg-[#0080FF]/20 text-xs font-bold text-[#00BBFF] mb-3">{{ item.specs.rec.title }}</span><ul class="space-y-2 text-xs text-[var(--text-muted)]"><li><strong class="text-[var(--text-muted)]">Процессор:</strong> {{ item.specs.rec.cpu }}</li><li><strong class="text-[var(--text-muted)]">ОЗУ:</strong> {{ item.specs.rec.ram }}</li><li><strong class="text-[var(--text-muted)]">Видеокарта:</strong> {{ item.specs.rec.gpu }}</li><li><strong class="text-[var(--text-muted)]">Накопитель:</strong> {{ item.specs.rec.disk }}</li></ul></div><p class="text-[11px] text-slate-500 mt-4 border-t border-white/[0.05] pt-2">{{ item.specs.rec.note }}</p></div></div><p v-else class="whitespace-pre-line">{{ item.a }}</p></div></div></div></section></template>
